# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0, help_text='Price in Euro')),
            ],
        ),
        migrations.CreateModel(
            name='HorseTechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, unique=True)),
                ('type', models.CharField(choices=[('T', 'Technology'), ('H', 'Horse')], default='T', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='horsetech',
            name='tags',
            field=models.ManyToManyField(to='viz.HorseTechTag'),
        ),
    ]
